pub mod adblock_commands;
pub mod app_lifecycle_commands;
pub mod audio_commands;
pub mod config_commands;
pub mod darkmode_commands;
pub mod download_commands;
pub mod find_commands;
pub mod workspace_commands;
pub mod zoom_commands;
