import { setAppConfigs, setAppStates, setActiveAppId } from "./uiStore";
import type { AppConfig } from "../types/config";
import type { AppStateInfo } from "../types/appState";

const mockAppConfigs: AppConfig[] = [
  {
    id: "whatsapp-personal",
    name: "WhatsApp",
    service_type: "whatsapp",
    url: "https://web.whatsapp.com",
    icon: "whatsapp",
    data_store_uuid: "550e8400-e29b-41d4-a716-446655440001",
    enabled: true,
    hibernated: false,
    audio_muted: false,
    user_agent: "",
    custom_css: "",
    custom_js: "",
    proxy: "",
    dark_mode: "off",
    dark_mode_brightness: 100,
    dark_mode_contrast: 90,
    dark_mode_sepia: 10,
    dark_mode_bg_color: "",
    dark_mode_text_color: "",
    hibernation_timeout_minutes: 15,
    download_directory: "~/Downloads",
    skip_download_dialog: false,
    workspace: "default",
    sidebar_section: "messaging",
    position: 0,
    notification_style: "full",
    adblock_enabled: true,
    zoom_level: 100,
    suppress_high_usage_alert: false,
  },
  {
    id: "slack-work",
    name: "Slack",
    service_type: "slack",
    url: "https://app.slack.com",
    icon: "slack",
    data_store_uuid: "550e8400-e29b-41d4-a716-446655440002",
    enabled: true,
    hibernated: true,
    audio_muted: false,
    user_agent: "",
    custom_css: "",
    custom_js: "",
    proxy: "",
    dark_mode: "dynamic",
    dark_mode_brightness: 100,
    dark_mode_contrast: 90,
    dark_mode_sepia: 0,
    dark_mode_bg_color: "",
    dark_mode_text_color: "",
    hibernation_timeout_minutes: 15,
    download_directory: "~/Downloads",
    skip_download_dialog: false,
    workspace: "default",
    sidebar_section: "messaging",
    position: 1,
    notification_style: "full",
    adblock_enabled: true,
    zoom_level: 100,
    suppress_high_usage_alert: false,
  },
  {
    id: "gmail-personal",
    name: "Gmail",
    service_type: "gmail",
    url: "https://mail.google.com",
    icon: "gmail",
    data_store_uuid: "550e8400-e29b-41d4-a716-446655440003",
    enabled: true,
    hibernated: false,
    audio_muted: true,
    user_agent: "",
    custom_css: "",
    custom_js: "",
    proxy: "",
    dark_mode: "off",
    dark_mode_brightness: 100,
    dark_mode_contrast: 100,
    dark_mode_sepia: 0,
    dark_mode_bg_color: "",
    dark_mode_text_color: "",
    hibernation_timeout_minutes: 30,
    download_directory: "~/Downloads",
    skip_download_dialog: false,
    workspace: "default",
    sidebar_section: "productivity",
    position: 2,
    notification_style: "private",
    adblock_enabled: true,
    zoom_level: 100,
    suppress_high_usage_alert: false,
  },
  {
    id: "discord-gaming",
    name: "Discord",
    service_type: "discord",
    url: "https://discord.com/app",
    icon: "discord",
    data_store_uuid: "550e8400-e29b-41d4-a716-446655440004",
    enabled: false,
    hibernated: false,
    audio_muted: false,
    user_agent: "",
    custom_css: "",
    custom_js: "",
    proxy: "",
    dark_mode: "off",
    dark_mode_brightness: 100,
    dark_mode_contrast: 100,
    dark_mode_sepia: 0,
    dark_mode_bg_color: "",
    dark_mode_text_color: "",
    hibernation_timeout_minutes: 0,
    download_directory: "~/Downloads",
    skip_download_dialog: false,
    workspace: "default",
    sidebar_section: "social",
    position: 3,
    notification_style: "full",
    adblock_enabled: false,
    zoom_level: 100,
    suppress_high_usage_alert: false,
  },
  {
    id: "telegram-personal",
    name: "Telegram",
    service_type: "telegram",
    url: "https://web.telegram.org",
    icon: "telegram",
    data_store_uuid: "550e8400-e29b-41d4-a716-446655440005",
    enabled: true,
    hibernated: false,
    audio_muted: false,
    user_agent: "",
    custom_css: "",
    custom_js: "",
    proxy: "",
    dark_mode: "off",
    dark_mode_brightness: 100,
    dark_mode_contrast: 100,
    dark_mode_sepia: 0,
    dark_mode_bg_color: "",
    dark_mode_text_color: "",
    hibernation_timeout_minutes: 15,
    download_directory: "~/Downloads",
    skip_download_dialog: false,
    workspace: "default",
    sidebar_section: "messaging",
    position: 4,
    notification_style: "full",
    adblock_enabled: true,
    zoom_level: 100,
    suppress_high_usage_alert: false,
  },
];

const mockAppStates: AppStateInfo[] = [
  {
    id: "whatsapp-personal",
    name: "WhatsApp",
    state: "active",
    badge_count: 3,
    current_url: "https://web.whatsapp.com",
  },
  {
    id: "slack-work",
    name: "Slack",
    state: "hibernated",
    badge_count: 12,
    current_url: "https://app.slack.com",
  },
  {
    id: "gmail-personal",
    name: "Gmail",
    state: "active",
    badge_count: null,
    current_url: "https://mail.google.com",
  },
  {
    id: "discord-gaming",
    name: "Discord",
    state: "disabled",
    badge_count: null,
    current_url: null,
  },
  {
    id: "telegram-personal",
    name: "Telegram",
    state: "active",
    badge_count: 0,
    current_url: "https://web.telegram.org",
  },
];

export function loadMockData() {
  setAppConfigs(mockAppConfigs);
  setAppStates(mockAppStates);
  setActiveAppId("whatsapp-personal");
}
